services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://delivery.massgrave.dev/dbmassgrave/en-us_windows_10_consumer_editions_version_22h2_updated_sep_2025_x64_dvd_4a22741d.iso?t=7HaS51NbsA083TcMsL4NMmazFbzKU43Z&P1=1758560281&P2=601&P3=2&P4=Kjflw15PLsqheu2iVG7S9wWTacCQml5d6cB6DPQEyWI%3D"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
